### ISSUE TITLE
How to save the result?

### ISSUE THREAD

**Issue by DominoA4** [rpdelaney-archive/python-chess-annotator#36]
Hello.  The process managed to start using the command: annotator -f 123.pgn -E stockfish21040618 -g 1 -t 3. In the console, 100 games were processed at a time.  How to save the result?

**Comment by rpdelaney** [comment]
You need to capture the standard output using whatever method is appropriate to your shell. In bash, something like this should work:

```
$ annotator -f 123.pgn -E stockfish21040618 -g 1 -t 3 | tee output.pgn
```

**Comment by DominoA4** [comment]
Help!
"Tee" is not internal or external A command executed by a program or batch file.

**Comment by rpdelaney** [comment]
I don't know what terminal you are using or what tools are available. You will have to look up how to do it in your own shell.

**Comment by DominoA4** [comment]
Thank you!  You helped me very much.  As a result, everything works like this:
annotator -f 123.pgn -e -stockfish_21040618_x64_modern -g 1 -t 3 > out.pgn
